### ISSUE TITLE
Component Model Support for Observe SDK

### ISSUE THREAD

**Issue by wikiwong** [dylibso/observe-sdk#126]
Enable support for the Observe SDK to execute and profile components. Since `wazero` does not yet support components, this issue is scoped to (in priority order):

- [ ] Rust (involves upgrading to Wasmtime 13 - https://github.com/bytecodealliance/wasmtime/releases/tag/v13.0.0) Ticket: https://github.com/dylibso/observe-sdk/issues/142
- [ ] JavaScript via https://github.com/bytecodealliance/jco

To test, we'll have to compile a component that has been instrumented. We should be able to do this manually with the [Rust Observe API](https://github.com/dylibso/observe-sdk/tree/main/observe-api/rust)

**Comment by neuronicnobody** [comment]
Reach out to Cosmonic after Kubecon in Nov.

**Comment by neuronicnobody** [comment]
Reached out...waiting for response

**Comment by neuronicnobody** [comment]
Currently blocked on Extism namespace / version updates

**Comment by G4Vi** [comment]
Rust support is in progress: Issue: https://github.com/dylibso/observe-sdk/issues/142 PR: https://github.com/dylibso/observe-sdk/pull/128

**Comment by neuronicnobody** [comment]
Moving work to #142
