### ISSUE TITLE
Rust Component Model Support for Observe SDK / Observe API

### ISSUE THREAD

**Issue by G4Vi** [dylibso/observe-sdk#142]
- [x] Change Observe API import module name to be compatible with component model
- [x] Change wasm-instr import module name to be compatible with component model
- [x] Updated Versioning https://github.com/dylibso/observe-sdk/issues/143
- [x] Error out when observe api is used in go and js sdks as it isn't implemented yet
- [x] Manually readd Go SDK changes from https://github.com/dylibso/observe-sdk/tree/chris/20231003-hack-in-component-support-with-go
- [x] Observe API component support
- [x] Rust-SDK component support

PR: https://github.com/dylibso/observe-sdk/pull/128

**Comment by G4Vi** [comment]
Removed Go and JS sdk items on the observe api, it hasn't been implemented yet for those sdks yet:
https://github.com/dylibso/observe-sdk/issues/68

**Comment by nilslice** [comment]
Thanks, @G4Vi -- we should keep this impl in mind as it has been shared around a bit I think: https://github.com/dylibso/observe-sdk/pull/123

Maybe we can just update this PR too.
