### ISSUE TITLE
[request] Need API keys for testing

### ISSUE THREAD

**Issue by shivanshu1333** [dylibso/observe-sdk#47]
Hi, I'd need the required API keys for testing https://github.com/dylibso/observe-sdk#instrumenting-wasm-module
I've reached out over email to get the keys but there's no response yet.

Any help would be greatly appreciated, thanks!

**Comment by nilslice** [comment]
Hi @shivanshu1333! Gladly - and sorry we haven't seen an email come through. Will check on that. 

can you email me steve[@]dylibso.coo and we will get you set up!

**Comment by shivanshu1333** [comment]
Thanks for the comment Steve, received. the keys over mail.
Excited to try out the SDK!!
