### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by wwkeyboard** [dylibso/observe-sdk#9]
The testing situation is currently grim, mostly done by hand. A first start is to unit test the individual modules. We also need to simplistic and well understood modules that we can run and verify that the captured events match what we expected from the module.
This will involve building at least one of those modules, and making a list of others we'll need. Then well need a way to test that the modules are events are being generated correctly, however we should not let changes to the adapters break these tests.

**Comment by wwkeyboard** [comment]
An integration test framework: https://github.com/dylibso/observe-sdk/pull/17

**Comment by bhelx** [comment]
Going to close since there was an action on #17. though I'd be open to anyone contributing more to the testing infra.
